server:
  port: 8080
  servlet:
    context-path: /activiti
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
#  activiti:
#    check-process-definitions: false
    
    #type: org.springframework.jdbc.datasource.DriverManagerDataSource
  freemarker:
    suffix: .html
    request-context-attribute: request
    
mybatis:
  mapper-locations:
  - classpath:*Mapper.xml
  type-aliases-package: com.yang.*
